version: "3.8"

services:
  apache:
    build:
      context: './apache2/'
    ports:
     - "80:80"
    volumes :
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    container_name: mongodb_container
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./src:/var/www/html:delegated
     - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
   platform: linux/x86_64 
   image: mysql:8
   env_file:
    - ./env/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
    - ./env/phpmyadmin.env
    ports:
      - 81:80
